### ISSUE TITLE
Idk whats causing this issue and config is broken if u can help me figure out?

### ISSUE THREAD

**Issue by Rexmen1** [jaqobb/rewardable-activities#3]
[17:08:08] [Server thread/INFO]: [RewardableActivities] Loading RewardableActivities v1.8.0
[17:08:08] [Server thread/INFO]: [RewardableActivities] Loading configuration...
[17:08:08] [Server thread/INFO]: [RewardableActivities] Loading rewardable activities...
[17:08:08] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing RewardableActivities v1.8.0 (Is it up to date?)
java.lang.NullPointerException: null
	at java.util.EnumMap.typeCheck(EnumMap.java:743) ~[?:?]
	at java.util.EnumMap.put(EnumMap.java:264) ~[?:?]
	at java.util.EnumMap.put(EnumMap.java:78) ~[?:?]
	at java.util.AbstractMap.putAll(AbstractMap.java:281) ~[?:?]
	at java.util.EnumMap.putAll(EnumMap.java:348) ~[?:?]
	at dev.jaqobb.rewardableactivities.data.RewardableActivityRepository.loadEntityKillRewardableActivities(RewardableActivityRepository.java:80) ~[?:?]
	at dev.jaqobb.rewardableactivities.data.RewardableActivityRepository.loadAllRewardableActivities(RewardableActivityRepository.java:62) ~[?:?]
	at dev.jaqobb.rewardableactivities.RewardableActivitiesPlugin.loadConfig(RewardableActivitiesPlugin.java:107) ~[?:?]
	at dev.jaqobb.rewardableactivities.RewardableActivitiesPlugin.onLoad(RewardableActivitiesPlugin.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.4.jar:git-Purpur-925]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:216) ~[patched_1.16.4.jar:git-Purpur-925]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:942) ~[patched_1.16.4.jar:git-Purpur-925]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180) ~[patched_1.16.4.jar:git-Purpur-925]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Rexmen1** [comment]
block:
  ownership-check:
    place: true
  break:
    ANCIENT_DEBRIS:
      default:
      - chance: 15.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 2.0
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 5.0
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 5.0
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 5.0
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 5.0
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 5.0
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 5.0
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"
    EMERALD_ORE:
      default:
      - chance: 15.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 2.0
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 5.0
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 5.0
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 5.0
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 5.0
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 5.0
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 5.0
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"        
    DIAMOND_ORE:
      default:
      - chance: 15.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 1.0
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 3.0
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 3.0
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 3.0
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 3.0
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 3.0
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 3.0
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"   
    COAL_ORE:
      default:
      - chance: 8.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 0.25
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 0.25
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 0.25
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 0.25
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 0.25
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 0.25
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 0.25
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"
    REDSTONE_ORE:
      default:
      - chance: 8.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 0.50
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 0.50
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 0.50
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 0.50
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 0.50
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 0.50
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 0.50
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"
    LAPIS_ORE:
      default:
      - chance: 8.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 1
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 1
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 1
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 1
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 1
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 1
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 1
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"
    NETHER_GOLD_ORE:
      default:
      - chance: 8.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 0.20
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 0.20
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 0.20
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 0.20
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 0.20
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 0.20
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 0.20
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"
    NETHER_QUARTZ_ORE:
      default:
      - chance: 8.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 0.15
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 0.15
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 0.15
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 0.15
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 0.15
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 0.15
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 0.15
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"
    NETHER_QUARTZ_ORE:
      default:
      - chance: 8.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 0.15
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 0.15
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 0.15
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 0.15
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 0.15
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 0.15
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 0.15
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"
    IRON_ORE:
      default:
      - chance: 8.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 0.50
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 0.50
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 0.50
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 0.50
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 0.50
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 0.50
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 0.50
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"        
    GOLD_ORE:
      default:
      - chance: 8.0
        commands:
        - "av user %player% addpoints 1"
      - chance: 1
        commands:
        - "ccrate give p Vote 1 %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l&l You have found a &bVote Crate Key"
      - chance: 1
        commands:
        - "mi give MATERIAL TIME %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &aTime Stone" 
      - chance: 1
        commands:
        - "mi give MATERIAL SOUL %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &bSoul Stone"
      - chance: 1
        commands:
        - "mi give MATERIAL MIND %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &eMind Stone"
      - chance: 1
        commands:
        - "mi give MATERIAL SPACE %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &9Space Stone"
      - chance: 1
        commands:
        - "mi give MATERIAL REALITY %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &4Reality Stone"
      - chance: 1
        commands:
        - "mi give MATERIAL POWER %player%"
        - "cmi bossbarmsg %player% &b&l(!)&7&l You have found a &5Power Stone"
  place:
    diamond_block:
      default:
        chance: 1.0
        commands:
        - "msg {player} placed a diamond block!"

entity:
  ownership-check:
    breed: false
    spawner: false
  kill:
    BAT:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    CAT:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    CHICKEN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    COD:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    COW:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    DONKEY:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    FOX:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    HORSE:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    OCELOT:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    PARROT:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    PIG:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    RABBIT:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    SHEEP:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    SQUID:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    STRIDER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    TURTLE:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    VILLAGER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    BEE:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    CAVE_SPIDER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    DOLPHIN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    ENDERMAN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    IRON_GOLEM:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    LLAMA:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    PANDA:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    PIGLIN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    POLAR_BEAR:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    SPIDER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    WOLF:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    ZOMBIFIED_PIGLIN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    BLAZE:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    CREEPER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    DROWNED:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    ELDER_GUARDIAN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    GHAST:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    GUARDIAN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    HOGLIN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    HUSK:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    MAGMA_CUBE:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    PHANTOM:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    PILLAGER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    RAVAGER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    SHULKER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    SILVERFISH:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    SKELETON:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    SLIME:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    STRAY:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    VEX:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    VINDICATOR:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    WITCH:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    WITHER_SKELTON:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    ZOGLIN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    ZOMBIE:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    ZOMBIE_VILLAGER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    WITHER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
  breed:
    HORSE:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    DONKEY:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."        
    COW:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    SHEEP:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."        
    PIG:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    CHICKEN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    WOLF:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    CAT:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."        
    OCELOT:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    RABBIT:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    TURTLE:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    LLAMA:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    PANDA:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    FOX:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    BEE:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    STRIDER:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    HOGLIN:
      default:
        chance: 8
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
item:
  fish:
    COD:
      default:
        chance: 8.0
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    SALMON:
      default:
        chance: 8.0
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."
    PUFFERFISH:
      default:
        chance: 8.0
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs." 
    TROPICAL_FISH:
      default:
        chance: 8.0
        commands:
        - "av user %player% addpoints 1"
        - "cmi actionbarmsg %player% &7[&c&l!&7] &bYou got 1 Token from killing mobs."

**Comment by Rexmen1** [comment]
https://paste.corebot.dev/ilaqotiraf.pl

**Comment by jaqobb** [comment]
Hey, the error seems to be a typo in the WITHER_SKELETON in entity kill rewardable activities section (you provided WITHER_SKELTON). You do also provide 2 times nether quartz ore in the block break rewardable activities section but that doesn't really do anything bad.

Let me know if fixing that wither skeleton typo fixes the issue for you. If so, I am also gonna release an update with more detailed error message.

**Comment by Rexmen1** [comment]
Ok thanks, it worked... I'm already loving this plugin a lot... Do you have any discord server?

**Comment by Rexmen1** [comment]
Also is there way to add farming items like carrot etc but only full grown ones....

**Comment by Rexmen1** [comment]
and fishing maybe not working
tried with 100% chance did nothing for the same config

**Comment by Rexmen1** [comment]
let me know ur discord server/tag so i can discuss more about plugins I can also donate for plugins and you can post them as free...

**Comment by jaqobb** [comment]
> Also is there way to add farming items like carrot etc but only full grown ones....

This is currently not possible but I am already thinking about implementing this.

> and fishing maybe not working
> tried with 100% chance did nothing for the same config

I personally tested fishing so I am gonna require more information if it does not work for you.

> Ok thanks, it worked... I'm already loving this plugin a lot... Do you have any discord server?

> let me know ur discord server/tag so i can discuss more about plugins I can also donate for plugins and you can post them as free...

I am currently in creation of one. While it is not ready to be publicly announced, feel free to join now: https://discord.gg/MZWabWZK6m
